### ISSUE TITLE
Not authorised to send Apple events ... Mojave issue

### ISSUE THREAD

**Issue by anbanpillay** [xuchunyang/grab-mac-link.el#1]
In the Mojave, cannot grab link. Error is "Not authorised to send Apple events to ...". Is there a workaround?

**Comment by xuchunyang** [comment]
I don't know. I haven't upgraded. I guess maybe Emacs's `do-applescript` simply doesn't work on Mojave, if it's true, this is probably an Emacs issue.

**Comment by xuchunyang** [comment]
I have upgraded to macOS Mojave and the error message I get is

> AppleScript error 1

Below is the version of my Emacs

```
(emacs-version)
;; =>
"GNU Emacs 27.0.50 (build 11, x86_64-apple-darwin18.0.0, NS appkit-1671.00 Version 10.14 (Build 18A391))
 of 2018-10-23"
```

Anyway, this is probably a bug of Emacs. According to https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave

> apps can no longer send Apple Events to other apps without user authorization.

Emacs now has to ask user for authorization, like Terminal.app

![screen shot 2018-10-28 at 5 19 54 am](https://user-images.githubusercontent.com/4550353/47609502-6165f980-da72-11e8-9fcf-26c58051b579.png)

**Comment by xuchunyang** [comment]
I just learnt the fix and it works here. Add the following to Emacs's `Info.plist` and restart Emacs.

```xml
<key>NSAppleEventsUsageDescription</key>
<string>Emacs requires permission to send some event to another application.</string>
```

The path to `Info.plist` for me is

```el
(expand-file-name "../Info.plist" invocation-directory)
;; => "/Users/xcy/src/emacs/nextstep/Emacs.app/Contents/Info.plist"
```

For more info, see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32888#8

**Comment by anbanpillay** [comment]
Great. Thanks for your assistance. 
Upgrading my emacs through brew to HEAD-c9487b2 seems to have fixed the issue. grab-link works now - a dialog pops up asking for permission and then all is well.
