### ISSUE TITLE
problem with (grab-mac-link 'safari 'org) the " " went inside the [ ] cause org-mode not able to open

### ISSUE THREAD

**Issue by dunkarooftop** [xuchunyang/grab-mac-link.el#2]
When I run the  (grab-mac-link 'safari 'org) the return

`[["www.google.com][Google"]]`

note the placement of the `"` mark. They should go outside the `[.  ]`

**Comment by xuchunyang** [comment]
Thanks for reporting. Should be fixed. I copied & pasted the AppleScript code from org-mac-link.el without too much understanding of it.

**Comment by dunkarooftop** [comment]
it's working fine now thank you so much!
